sudo: required
services:
  - docker

before_install:
  - docker build -t luis-garcia17/docker-react -f Dockerfile.dev . # This might be my github username instead of my docker username

script:
  - docker run -e CI=true luis-garcia17/docker-react npm run test # Same thing

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-453681424228"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"